---
#####
# Main configuration file
#####

# Vars used to manage podman images
imgName: "httpd"
imgTags: ["v1", "v2", "prod"]
tagDest: "{{ imgTags[2] }}"
registryHost: "192.168.1.38"

# Vars used to manage RHEL images
imageIDOrig: "7b7bbe552b98fa123a4148c3a136264283f041e963eb536277e0235df751f6ba"
imageString: "v1"
fileImgSignature: "/etc/greenboot/orig.txt"

# OS commands
podmanCmd: "/usr/bin/podman"
systemctlCmd: "/usr/bin/systemctl"
sudoCmd: "/usr/bin/sudo"
catCmd: "/usr/bin/cat"
awkCmd: "/usr/bin/awk"
...
